name: Tests

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nim: ["2.2.0", "stable", "devel"]

    name: Nim ${{ matrix.nim }}
    steps:
      - name: Setup Nim Enviroment
        uses: actions/checkout@v6

      - uses: iffy/install-nim@v5
        with:
          version: ${{ matrix.nim }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache choosenim
        id: cache-choosenim
        uses: actions/cache@v5
        with:
          path: ~/.nimble
          key: nimble-${{ hashFiles('*.nimble') }}

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Install nim dependencies
        continue-on-error: true
        run: nimble update && nimble install

      - name: Run Tests
        run: nimble test

      - name: Test doc examples
        run: nimble doc --warningAsError:BrokenLink:on --project src/ponairi.nim

  deploy:
    name: Documentation
    needs: test
    permissions:
      pages: write # To deploy to Pages
      id-token: write # Verify deployment
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v6

      - name: "Setup nim"
        uses: jiro4989/setup-nim-action@v2

      - uses: iffy/install-nim@v5
        with:
          version: stable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build documentation"
        uses: ire4ever1190/nim-docs-action@v2
        with:
          main-file: "src/ponairi.nim"
          deploy: "pages"
